from logging import INFO


# Basic Settings
DELTA = 1e-7

# Hyper Parameters
NORMALIZING_FLOW_LAYER_NUM = 16
LEARNING_RATE = 1e-3
BETA1 = 0.9
BETA2 = 0.999
BATCH_SIZE = 1024
ITERATION = 30000

# Figure Settings
SAVE_FIGURE_INTERVAL = 1000
NUMBER_OF_SAMPLES_FOR_VISUALIZE = 8192
FIGURE_RESOLUTION = 1000
FIGURE_SIZE = 6
AXIS_INVISIBLE = True
FIGURE_DIR = './figure'

# Logging Settings
LOG_LEVEL = INFO